apiVersion: apps/v1
kind: Deployment 
metadata:
  name: infra-observer
  namespace: graywatcher
  labels:
    app: infra-observer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: infra-observer
  template:
    metadata:
      labels:
        app: infra-observer
    spec:
      serviceAccountName: infra-observer-sa
      containers:
      - name: infra-observer
        image: vera5660/infra-observer:v1.3
        imagePullPolicy: Always
        env:
          - name: VERDICT_SERVER_URL
            value: "http://verdict-server.graywatcher.svc.cluster.local"
          
          - name: INTERVAL
            value: "10"
            
        resources:
          limits:
            memory: 256Mi
            cpu: 500m
          requests:
            cpu: 100m
            memory: 128Mi
      terminationGracePeriodSeconds: 30