# Service Account Definition
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kubernetes.io/enforce-mountable-secrets: "true"
  name: infra-observer-sa
  namespace: graywatcher

---
# ClusterRole Definition
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: infra-observer
rules:
- apiGroups: [""]
  resources: ["pods", "nodes"]
  verbs: ["get", "list"]

---
# ClusterRoleBinding Definition
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: infra-observer
subjects:
- kind: ServiceAccount
  name: infra-observer-sa
  namespace: graywatcher
roleRef:
  kind: ClusterRole
  name: infra-observer
  apiGroup: rbac.authorization.k8s.io
